language: c
before_install:
  - echo "Travis CI starts"
  - sudo apt-get update
  - sudo apt-get build-essential libgtk2.0-dev make
install: make get-deps
script:
  - make
after_script:
  - echo "Travis CI ends"
